// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxdsW5ls3M182S2lfy098lddbXsTIdIk',
    appId: '1:655394207734:android:37933d7e3fcec8a5d9f9d7',
    messagingSenderId: '655394207734',
    projectId: 'ecomereceapp-d9e2f',
    storageBucket: 'ecomereceapp-d9e2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcm9SiPqsvHYDGrvDTNJ6SQ51NzZGyDo',
    appId: '1:655394207734:ios:8e341a523865a92ad9f9d7',
    messagingSenderId: '655394207734',
    projectId: 'ecomereceapp-d9e2f',
    storageBucket: 'ecomereceapp-d9e2f.firebasestorage.app',
    iosBundleId: 'com.example.ecomreceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgyJErO970BXyJK-FIEq3W2DBDaS-ovXE',
    appId: '1:655394207734:web:ed52f86bede7339ad9f9d7',
    messagingSenderId: '655394207734',
    projectId: 'ecomereceapp-d9e2f',
    authDomain: 'ecomereceapp-d9e2f.firebaseapp.com',
    storageBucket: 'ecomereceapp-d9e2f.firebasestorage.app',
  );
}
